# Generated by Django 4.2.2 on 2023-06-25 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='Actor/')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='Director/')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('r_date', models.DateField(default=django.utils.timezone.now)),
                ('actors', models.ManyToManyField(to='moviebase.actor')),
                ('directors', models.ManyToManyField(to='moviebase.director')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebase.gender'),
        ),
        migrations.AddField(
            model_name='actor',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebase.gender'),
        ),
    ]
